# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main
  
pool:
  vmImage: ubuntu-latest

variables:
  disable.coverage.autogenerate: false 
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: "dotnet build"
  inputs:
    command: 'build'
    projects: './src/services/FH.ParcelLogistics.Services/FH.ParcelLogistics.Services.csproj'
    
- task: DotNetCoreCLI@2
  displayName: "dotnet test"
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
    publishTestResults: true

- task: DotNetCoreCLI@2 
  displayName: 'Create .NET local manifest' 
  inputs: 
    command: custom 
    custom: new 
    arguments: 'tool-manifest'

- task: DotNetCoreCLI@2 
  displayName: 'Install ReportGenerator' 
  inputs: 
    command: custom 
    custom: tool 
    arguments: 'install --global dotnet-reportgenerator-globaltool' 

- task: DotNetCoreCLI@2 
  displayName: 'Merge code coverage files' 
  inputs: 
    command: custom 
    custom: tool 
    arguments: 'run reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/build_reports/code_coverage -reporttypes:HtmlInline_AzurePipelines;Cobertura' 
  
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'    

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './src/services/FH.ParcelLogistics.Services/bin/$(buildConfiguration)/'
    ArtifactName: 'drop'
    publishLocation: 'Container'