:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\FH.ParcelLogistics.Services
dotnet build src\FH.ParcelLogistics.Services
echo Now, run the following to start the project: dotnet run -p src\FH.ParcelLogistics.Services\FH.ParcelLogistics.Services.csproj --launch-profile web.
echo.
