/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.22.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using FH.ParcelLogistics.BusinessLogic.Interfaces;
using FH.ParcelLogistics.Services.Attributes;
using FH.ParcelLogistics.Services.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace FH.ParcelLogistics.Services.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class LogisticsPartnerApiController : ControllerBase
    {
        private readonly IMapper _mapper;
        private readonly ITransitionLogic _transitionLogic; 
        private readonly ILogger<ControllerBase> _logger;

        public LogisticsPartnerApiController(IMapper mapper, ITransitionLogic transitionLogic, ILogger<ControllerBase> logger) { 
            _mapper = mapper; 
            _transitionLogic = transitionLogic;
            _logger = logger;
        }

        /// <summary>
        /// Transfer an existing parcel into the system from the service of a logistics partner. 
        /// </summary>
        /// <param name="trackingId">The tracking ID of the parcel. E.g. PYJRB4HZ6 </param>
        /// <param name="parcel"></param>
        /// <response code="200">Successfully transitioned the parcel</response>
        /// <response code="400">The operation failed due to an error.</response>
        /// <response code="409">A parcel with the specified trackingID is already in the system.</response>
        [HttpPost]
        [Route("/parcel/{trackingId}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("TransitionParcel")]
        [SwaggerResponse(statusCode: 200, type: typeof(NewParcelInfo), description: "Successfully transitioned the parcel")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "The operation failed due to an error.")]
        [SwaggerResponse(statusCode: 409, type: typeof(Error), description: "A parcel with the specified trackingID is already in the system.")]
        public virtual IActionResult TransitionParcel(
            [FromRoute(Name = "trackingId")][Required][RegularExpression("^[A-Z0-9]{9}$")] string trackingId,
            [FromBody] Parcel parcel)
        {
            var parcelEntity = _mapper.Map<BusinessLogic.Entities.Parcel>(parcel);
            
            try{
                var result = _transitionLogic.TransitionParcel(trackingId, parcelEntity);
                return StatusCode(StatusCodes.Status200OK, _mapper.Map<NewParcelInfo>(result));
            } catch(BLValidationException e){
                _logger.LogError(e, $"TransitionParcel: [trackingId:{trackingId}] invalid");
                return StatusCode(StatusCodes.Status400BadRequest, new Error(){ErrorMessage = e.Message});
            } catch(BLConflictException e){
                _logger.LogError(e, $"TransitionParcel: [trackingId:{trackingId}] already in the system");
                return StatusCode(StatusCodes.Status409Conflict, new Error(){ErrorMessage = e.Message});
            }
        }
    }
}