/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.22.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using FH.ParcelLogistics.Services.Converters;

namespace FH.ParcelLogistics.Services.DTOs
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Parcel 
    {
        /// <summary>
        /// Gets or Sets Weight
        /// </summary>
        [Required]
        [DataMember(Name="weight", EmitDefaultValue=true)]
        public float Weight { get; set; }

        /// <summary>
        /// Gets or Sets Recipient
        /// </summary>
        [Required]
        [DataMember(Name="recipient", EmitDefaultValue=false)]
        public Recipient Recipient { get; set; }

        /// <summary>
        /// Gets or Sets Sender
        /// </summary>
        [Required]
        [DataMember(Name="sender", EmitDefaultValue=false)]
        public Recipient Sender { get; set; }

    }
}
