/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.22.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using FH.ParcelLogistics.Services.Converters;

namespace FH.ParcelLogistics.Services.DTOs {
	/// <summary>
	/// 
	/// </summary>
	[DataContract]
	public partial class Recipient {
		/// <summary>
		/// Name of person or company.
		/// </summary>
		/// <value>Name of person or company.</value>
		[Required]
		[DataMember(Name = "name", EmitDefaultValue = false)]
		public string Name { get; set; }

		/// <summary>
		/// Street
		/// </summary>
		/// <value>Street</value>
		[Required]
		[DataMember(Name = "street", EmitDefaultValue = false)]
		public string Street { get; set; }

		/// <summary>
		/// Postalcode
		/// </summary>
		/// <value>Postalcode</value>
		[Required]
		[DataMember(Name = "postalCode", EmitDefaultValue = false)]
		public string PostalCode { get; set; }

		/// <summary>
		/// City
		/// </summary>
		/// <value>City</value>
		[Required]
		[DataMember(Name = "city", EmitDefaultValue = false)]
		public string City { get; set; }

		/// <summary>
		/// Country
		/// </summary>
		/// <value>Country</value>
		[Required]
		[DataMember(Name = "country", EmitDefaultValue = false)]
		public string Country { get; set; }
	}
}